### ISSUE TITLE
[question] Is it a deliberate design choice that Pair's key & value are not public?

### ISSUE THREAD

**Issue by RLovelett** [jpsim/Yams#20]
It seems that [`Pair`'s `key` & `value` are not `public`](https://github.com/jpsim/Yams/blob/8551f6d0841e28b31ba5f793bed11f215295c54d/Sources/Yams/Node.swift#L122-L123) which makes this inaccessible outside the module. Is this a deliberate design choice?

If so how is someone supposed to find the value of a `Node`?

**Comment by norio-nomura** [comment]
I've made them `internal` as implementation details. Since direct access to them may result in operations out of the specification of YAML.
In the latest master, the `mapping` property behaves like` Dictionary`:
https://github.com/jpsim/Yams/blob/master/Tests/YamsTests/NodeTests.swift#L126-L156
I guess this is enough, but would you please tell me if there is a reason to need direct access that can not be covered by these?

**Comment by norio-nomura** [comment]
First I wondered whether `Node.mapping` should have`[Pair<Node>]` or `Dictionary<Node, Node>`, but respecting the very first implementation `[Pair<Node>] `Was selected.
Now I am thinking that it would be better to change to `Dictionary<Node, Node>` as a result of implementing the whole story.

**Comment by RLovelett** [comment]
Sorry for the delayed response. Had to step away for this for awhile.

Ultimately I cannot give a really good explanation for what I'm trying to do yet because I'm still trying to figure out what I want to do. Therefore it's unfair of me to make requests of you that I cannot articulate myself. I'm going to close this, revert to 0.1.4 (where I know my code worked); once things stabilize I'll check out PR #22 and the changes you've made on master.

Thank you for the thoughtful responses.
