### ISSUE TITLE
`Array.construct_omap` is identical to `Array.construct_pairs`

### ISSUE THREAD

**Issue by jpsim** [jpsim/Yams#60]
Not sure if this is a real issue or not, but the code for [`Array.construct_omap`](https://github.com/jpsim/Yams/blob/0.3.7/Sources/Yams/Constructor.swift#L333-L341) is identical to [`Array.construct_pairs`](https://github.com/jpsim/Yams/blob/0.3.7/Sources/Yams/Constructor.swift#L343-L351).

Is this a mistake, or is it expected that they're the same? If it's expected, why not remove one or at least have it forward to the other to remove the code duplication?

**Comment by norio-nomura** [comment]
When I changed to use `yaml_parser_parse ()`, I implemented most of it with reference to PyYAML.
Both of `Array.construct_omap` and `Array.construct_pairs` are following:
https://github.com/yaml/pyyaml/blob/master/lib3/yaml/constructor.py#L338-L379

It is not a mistake that these codes are the same, but the reason why the same code is written is because "PyYAML was written like that".

**Comment by jpsim** [comment]
😊 ok
